services:
  init-nginx:
    image: alpine:3.20
    container_name: init-nginx
    volumes:
      - ./nginx:/nginx
    entrypoint: /bin/sh
    command:
      - -c
      - |
        mkdir -p /nginx/conf.d
        if [ ! -f /nginx/conf.d/upstream.conf ]; then
          cp /nginx/upstream-blue.conf /nginx/conf.d/upstream.conf
          echo "upstream.conf created from upstream-blue.conf"
        else
          echo "upstream.conf already exists"
        fi
    networks:
      - chat-net

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      init-nginx:
        condition: service_completed_successfully
      app-blue:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - chat-net

  app-blue:
    image: ${BLUE_IMAGE:-ghcr.io/sea-of-fertility/real-time-chat:latest}
    container_name: app-blue
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - chat-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 3

  app-green:
    image: ${GREEN_IMAGE:-ghcr.io/sea-of-fertility/real-time-chat:latest}
    container_name: app-green
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - chat-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 3

  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USERNAME} -d $${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - chat-net

networks:
  chat-net:
    driver: bridge

volumes:
  pgdata:
