spring:
  application:
    name: real-time-chat
  h2:
    console:
      enable: true
      path: /h2-console
  r2dbc:
    url: r2dbc:h2:mem:///test
    username: sa
    password:

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.springframework.r2dbc: DEBUG
