server:
  port: 8080
  servlet:
    context-path: /api
    async:
      timeout: 3600000

spring:
  profiles:
    active: local
  messages:
    basename: messages
    encoding: UTF-8
  application:
    name: real-time-chat
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/chat
    username: sa
    password: 1234

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.springframework.r2dbc: DEBUG

app:
  jwt:
    secret-key: local-dev-secret-key-that-is-at-least-32-bytes-long
    access-token-expiration: 1800000
    refresh-token-expiration: 86400000
